# Generated by Django 4.0.8 on 2023-01-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingssync", "0001_initial_new_2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="syncedcharacter",
            old_name="last_sync",
            new_name="last_update_at",
        ),
        migrations.RenameField(
            model_name="syncmanager",
            old_name="last_sync",
            new_name="last_update_at",
        ),
        migrations.RemoveField(
            model_name="syncmanager",
            name="last_error",
        ),
    ]
