# Generated by Django 4.0.9 on 2023-02-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "standingssync",
            "0002_rename_last_sync_syncedcharacter_last_update_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncedcharacter",
            name="last_error",
        ),
    ]
