# Generated by Django 4.0.9 on 2023-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingssync", "0003_remove_syncedcharacter_last_error"),
    ]

    operations = [
        migrations.RenameField(
            model_name="syncedcharacter",
            old_name="version_hash",
            new_name="version_hash_manager",
        ),
        migrations.AddField(
            model_name="syncedcharacter",
            name="version_hash_character",
            field=models.CharField(default="", max_length=32),
        ),
    ]
