# Generated by Django 4.0.9 on 2023-02-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "standingssync",
            "0004_rename_version_hash_syncedcharacter_version_hash_manager_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncedcharacter",
            name="version_hash_character",
        ),
        migrations.RemoveField(
            model_name="syncedcharacter",
            name="version_hash_manager",
        ),
    ]
