# Generated by Django 4.0.9 on 2023-02-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "standingssync",
            "0005_remove_syncedcharacter_version_hash_character_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="syncedcharacter",
            old_name="last_update_at",
            new_name="last_sync_at",
        ),
        migrations.RenameField(
            model_name="syncmanager",
            old_name="last_update_at",
            new_name="last_sync_at",
        ),
    ]
